# Generated by tools/bindgen.v from @[py_export] functions in vpg.v.
# Do not edit by hand.

from __future__ import annotations

import os
import queue
import threading
from pathlib import Path
from cffi import FFI

ffi = FFI()
ffi.cdef("""
void vpg_py_set_exec_path(char * path);
void * vpg_py_open(char * data_dir, char * user, char * db);
int vpg_py_initdb(char * data_dir, char * user);
char * vpg_py_query(void * handle, char * query);
int vpg_py_vacuum(void * handle);
int vpg_py_analyze(void * handle);
int vpg_py_maintain(void * handle);
void vpg_py_close(void * handle);
char * vpg_py_last_error(void);
void vpg_py_free(void * ptr);
""")


def _default_library_path() -> Path:
    return Path(__file__).resolve().parents[1] / "build" / "libvpg_python.so"


def _load_library():
    path = Path(os.environ.get("VPG_PY_LIBRARY", _default_library_path()))
    flags = getattr(os, "RTLD_NOW", 2) | getattr(os, "RTLD_GLOBAL", 0)
    return ffi.dlopen(str(path), flags)


lib = _load_library()
_task_queue: queue.Queue = queue.Queue()
_worker_lock = threading.Lock()
_worker_started = False
_worker_state = threading.local()


def _db_worker() -> None:
    _worker_state.in_worker = True
    while True:
        fn, args, result_queue = _task_queue.get()
        try:
            result_queue.put((True, fn(*args)))
        except BaseException as exc:
            result_queue.put((False, exc))


def _ensure_worker() -> None:
    global _worker_started
    if _worker_started:
        return
    with _worker_lock:
        if _worker_started:
            return
        thread = threading.Thread(target=_db_worker, name="vpg-db", daemon=True)
        thread.start()
        _worker_started = True


def _call(fn, *args):
    if getattr(_worker_state, "in_worker", False):
        return fn(*args)
    _ensure_worker()
    result_queue: queue.Queue = queue.Queue(maxsize=1)
    _task_queue.put((fn, args, result_queue))
    ok, value = result_queue.get()
    if ok:
        return value
    raise value


def _tool_path(name: str) -> Path:
    return Path(__file__).resolve().parents[1] / "postgresql" / "installed" / "bin" / name


def _set_exec_path(name: str) -> None:
    path = _tool_path(name)
    if path.exists():
        _call(lib.vpg_py_set_exec_path, str(path).encode("utf-8"))


def _bytes(value: str | bytes) -> bytes:
    if isinstance(value, bytes):
        return value
    return value.encode("utf-8")


def _last_error() -> str:
    raw = _call(lib.vpg_py_last_error)
    if raw == ffi.NULL:
        return "unknown vpg error"
    return ffi.string(raw).decode("utf-8", errors="replace")


class VPGError(RuntimeError):
    pass


def initdb(data_dir: str, user: str = "postgres") -> None:
    _set_exec_path("initdb")
    rc = _call(lib.vpg_py_initdb, _bytes(data_dir), _bytes(user))
    if rc != 0:
        raise VPGError(_last_error())


class EmbeddedPostgres:
    def __init__(self, data_dir: str, user: str = "postgres", db: str = "postgres"):
        _set_exec_path("postgres")
        self._handle = _call(lib.vpg_py_open, _bytes(data_dir), _bytes(user), _bytes(db))
        if self._handle == ffi.NULL:
            raise VPGError(_last_error())

    def query(self, sql: str) -> str:
        def run_query():
            result = lib.vpg_py_query(self._handle, _bytes(sql))
            if result == ffi.NULL:
                raise VPGError(_last_error())
            try:
                return ffi.string(result).decode("utf-8")
            finally:
                lib.vpg_py_free(result)
        return _call(run_query)

    def vacuum(self) -> None:
        if _call(lib.vpg_py_vacuum, self._handle) != 0:
            raise VPGError(_last_error())

    def analyze(self) -> None:
        if _call(lib.vpg_py_analyze, self._handle) != 0:
            raise VPGError(_last_error())

    def maintain(self) -> None:
        if _call(lib.vpg_py_maintain, self._handle) != 0:
            raise VPGError(_last_error())

    def close(self) -> None:
        if self._handle != ffi.NULL:
            _call(lib.vpg_py_close, self._handle)
            self._handle = ffi.NULL

    def __enter__(self) -> "EmbeddedPostgres":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass


def get_server(data_dir: str, user: str = "postgres", db: str = "postgres") -> EmbeddedPostgres:
    initdb(data_dir, user)
    return EmbeddedPostgres(data_dir, user, db)
