module main

import os
import strings
import v.ast
import v.parser
import v.pref

const source_file = 'vpg.v'
const output_file = 'vpg/vpg_cffi.py'

struct ExportedFn {
	c_name string
	v_name string
	params []Param
	ret    string
}

struct Param {
	name string
	typ  string
}

fn attr_arg(attrs []ast.Attr, name string) ?string {
	for attr in attrs {
		if attr.name == name {
			if attr.has_arg {
				return attr.arg
			}
			return ''
		}
	}
	return none
}

fn c_type(v_type string) !string {
	return match v_type {
		'void' { 'void' }
		'voidptr' { 'void *' }
		'&char' { 'char *' }
		'int' { 'int' }
		else { error('unsupported exported type ${v_type}') }
	}
}

fn c_decl(item ExportedFn) !string {
	mut params := []string{}
	for param in item.params {
		params << '${c_type(param.typ)!} ${param.name}'
	}
	if params.len == 0 {
		params << 'void'
	}
	return '${c_type(item.ret)!} ${item.c_name}(${params.join(', ')});'
}

fn exported_functions() ![]ExportedFn {
	mut table := ast.new_table()
	prefs := pref.new_preferences()
	file := parser.parse_file(source_file, mut table, .skip_comments, prefs)
	mut out := []ExportedFn{}
	for stmt in file.stmts {
		if stmt is ast.FnDecl {
			if _ := attr_arg(stmt.attrs, 'py_export') {
				export_name := attr_arg(stmt.attrs, 'export') or {
					return error('${stmt.name} has @[py_export] but no @[export]')
				}
				mut params := []Param{}
				for param in stmt.params {
					params << Param{
						name: param.name
						typ:  table.type_to_str(param.typ)
					}
				}
				out << ExportedFn{
					c_name: export_name
					v_name: stmt.name
					params: params
					ret:    table.type_to_str(stmt.return_type)
				}
			}
		}
	}
	return out
}

fn python_wrapper(exports []ExportedFn) !string {
	mut cdefs := []string{}
	for item in exports {
		cdefs << c_decl(item)!
	}

	mut b := strings.new_builder(4096)
	b.writeln('# Generated by tools/bindgen.v from @[py_export] functions in vpg.v.')
	b.writeln('# Do not edit by hand.')
	b.writeln('')
	b.writeln('from __future__ import annotations')
	b.writeln('')
	b.writeln('import os')
	b.writeln('from pathlib import Path')
	b.writeln('from cffi import FFI')
	b.writeln('')
	b.writeln('ffi = FFI()')
	b.writeln('ffi.cdef("""')
	for line in cdefs {
		b.writeln(line)
	}
	b.writeln('""")')
	b.writeln('')
	b.writeln('')
	b.writeln('def _default_library_path() -> Path:')
	b.writeln('    return Path(__file__).resolve().parents[1] / "build" / "libvpg_python.so"')
	b.writeln('')
	b.writeln('')
	b.writeln('def _load_library():')
	b.writeln('    path = Path(os.environ.get("VPG_PY_LIBRARY", _default_library_path()))')
	b.writeln('    flags = getattr(os, "RTLD_NOW", 2) | getattr(os, "RTLD_GLOBAL", 0)')
	b.writeln('    return ffi.dlopen(str(path), flags)')
	b.writeln('')
	b.writeln('')
	b.writeln('lib = _load_library()')
	b.writeln('')
	b.writeln('')
	b.writeln('def _tool_path(name: str) -> Path:')
	b.writeln('    return Path(__file__).resolve().parents[1] / "postgresql" / "installed" / "bin" / name')
	b.writeln('')
	b.writeln('')
	b.writeln('def _set_exec_path(name: str) -> None:')
	b.writeln('    path = _tool_path(name)')
	b.writeln('    if path.exists():')
	b.writeln('        lib.vpg_py_set_exec_path(str(path).encode("utf-8"))')
	b.writeln('')
	b.writeln('')
	b.writeln('def _bytes(value: str | bytes) -> bytes:')
	b.writeln('    if isinstance(value, bytes):')
	b.writeln('        return value')
	b.writeln('    return value.encode("utf-8")')
	b.writeln('')
	b.writeln('')
	b.writeln('def _last_error() -> str:')
	b.writeln('    raw = lib.vpg_py_last_error()')
	b.writeln('    if raw == ffi.NULL:')
	b.writeln('        return "unknown vpg error"')
	b.writeln('    return ffi.string(raw).decode("utf-8", errors="replace")')
	b.writeln('')
	b.writeln('')
	b.writeln('class VPGError(RuntimeError):')
	b.writeln('    pass')
	b.writeln('')
	b.writeln('')
	b.writeln('def initdb(data_dir: str, user: str = "postgres") -> None:')
	b.writeln('    _set_exec_path("initdb")')
	b.writeln('    rc = lib.vpg_py_initdb(_bytes(data_dir), _bytes(user))')
	b.writeln('    if rc != 0:')
	b.writeln('        raise VPGError(_last_error())')
	b.writeln('')
	b.writeln('')
	b.writeln('class EmbeddedPostgres:')
	b.writeln('    def __init__(self, data_dir: str, user: str = "postgres", db: str = "postgres"):')
	b.writeln('        _set_exec_path("postgres")')
	b.writeln('        self._handle = lib.vpg_py_open(_bytes(data_dir), _bytes(user), _bytes(db))')
	b.writeln('        if self._handle == ffi.NULL:')
	b.writeln('            raise VPGError(_last_error())')
	b.writeln('')
	b.writeln('    def query(self, sql: str) -> str:')
	b.writeln('        result = lib.vpg_py_query(self._handle, _bytes(sql))')
	b.writeln('        if result == ffi.NULL:')
	b.writeln('            raise VPGError(_last_error())')
	b.writeln('        try:')
	b.writeln('            return ffi.string(result).decode("utf-8")')
	b.writeln('        finally:')
	b.writeln('            lib.vpg_py_free(result)')
	b.writeln('')
	b.writeln('    def vacuum(self) -> None:')
	b.writeln('        if lib.vpg_py_vacuum(self._handle) != 0:')
	b.writeln('            raise VPGError(_last_error())')
	b.writeln('')
	b.writeln('    def analyze(self) -> None:')
	b.writeln('        if lib.vpg_py_analyze(self._handle) != 0:')
	b.writeln('            raise VPGError(_last_error())')
	b.writeln('')
	b.writeln('    def maintain(self) -> None:')
	b.writeln('        if lib.vpg_py_maintain(self._handle) != 0:')
	b.writeln('            raise VPGError(_last_error())')
	b.writeln('')
	b.writeln('    def close(self) -> None:')
	b.writeln('        if self._handle != ffi.NULL:')
	b.writeln('            lib.vpg_py_close(self._handle)')
	b.writeln('            self._handle = ffi.NULL')
	b.writeln('')
	b.writeln('    def __enter__(self) -> "EmbeddedPostgres":')
	b.writeln('        return self')
	b.writeln('')
	b.writeln('    def __exit__(self, exc_type, exc, tb) -> None:')
	b.writeln('        self.close()')
	b.writeln('')
	b.writeln('    def __del__(self):')
	b.writeln('        try:')
	b.writeln('            self.close()')
	b.writeln('        except Exception:')
	b.writeln('            pass')
	b.writeln('')
	b.writeln('')
	b.writeln('def get_server(data_dir: str, user: str = "postgres", db: str = "postgres") -> EmbeddedPostgres:')
	b.writeln('    initdb(data_dir, user)')
	b.writeln('    return EmbeddedPostgres(data_dir, user, db)')
	return b.str()
}

fn main() {
	exports := exported_functions() or {
		eprintln(err)
		exit(1)
	}
	if exports.len == 0 {
		eprintln('no @[py_export] functions found')
		exit(1)
	}
	os.mkdir_all(os.dir(output_file))!
	os.write_file(output_file, python_wrapper(exports)!)!
}
